"""empty message

Revision ID: 424ab66caad8
Revises: a53472c4ecdd
Create Date: 2020-03-06 01:42:22.550099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424ab66caad8'
down_revision = 'a53472c4ecdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_flag')
    # ### end Alembic commands ###
